# EnvironmentVariableList:
#   Global:
#     GDC_DOCKER_COMPOSE_PROJECT_NAME: '<folder name>'
#     VXL_IMAGE_NS: vxlinternal
#     VXL_IMAGE_PROJ: default
#     VXL_CONTAINER_NS: vxlinternal
#     VXL_CONTAINER_PROJ: default
#   Project:
#     VXL_AFS_SECRETS_FOLDER:

version: '3'
services:
  minio1:
    image: minio/minio:RELEASE.2019-04-09T01-22-30Z

    container_name: ${VXL_CONTAINER_NS:-vxlinternal}-${VXL_CONTAINER_PROJ:-default}-fitwatcher-minio1

    volumes:
      - ../minio_data:/data

    ports:
      - "${VXL_MINIO_PORT:-9000}:9000"

    environment:
      MINIO_ACCESS_KEY: minioxxxak
      MINIO_SECRET_KEY: minioxxxsk

    command: server /data


  webserver:
    image: ${VXL_IMAGE_NS:-vxlinternal}/${VXL_IMAGE_PROJ:-default}/fitwatcherwebserver:0.2.0
    build:
      context: .

    container_name: ${VXL_CONTAINER_NS:-vxlinternal}-${VXL_CONTAINER_PROJ:-default}-fitwatcher-webserver
    links:
      - "minio1:minio1"

    environment:
      VXL_AFS_SECRETS_FOLDER: ${VXL_AFS_SECRETS_FOLDER}

    depends_on:
      - "minio1"

    volumes:
      - ".:/usr/volumes/src/"
      - "../secrets:${VXL_AFS_SECRETS_FOLDER}"

    command: bash docker-cmd.sh

    # ports:
    #   - "443:443"
    #   - "80:80"

networks:
  default:
    external:
      name: mainginx_net
